version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: "update-score:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  api-1:
    container_name: api-1
    build: ./api-1
    ports:
      - 4001:4001
    volumes:
      - ./api-1:/api-1
    depends_on:
      - kafka
  api-2:
    container_name: api-2
    build: ./api-2
    ports:
      - 4002:4002
    volumes:
      - ./api-2:/api-2
    depends_on:
      - kafka
  api-3:
    container_name: api-3
    build: ./api-3
    ports:
      - 4003:4003
    volumes:
      - ./api-3:/api-3
    depends_on:
      - kafka
  socket:
    container_name: socket
    build: ./socket
    ports:
      - 5000:5000
    volumes:
      - ./socket:/socket
    depends_on:
      - kafka
